### ISSUE TITLE
Can not find "FirebaseRemoteConfig" singleton.

### ISSUE THREAD

**Issue by maihomahesh** [DrMoriarty/godot-firebase-remoteconfig#1]
I installed the plugin with nativelib. It is also ticked in plugins section of android export window. However, `Engine.has_singleton("FirebaseRemoteConfig")` returns false. I don't know why this is happening and I need help. Thank you.

**Comment by DrMoriarty** [comment]
Check if you enabled custom build for Android.

**Comment by maihomahesh** [comment]
I have enabled that too. By the way, I also tried another plugin "Network", and Engine has "Network". Same process.

**Comment by DrMoriarty** [comment]
Could you show your app starting logs?
Engine prepared plugins at start and logs can contain some errors.

**Comment by maihomahesh** [comment]
The log is too long. Didn't know whether to paste all. So just showing these errors if it helps for you to understand.
`02-11 15:31:07.995 29572 29572 W .callbreakgodo: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
02-11 15:31:08.295 29572 29572 W GodotPluginRegistry: 	at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:176)
02-11 15:31:08.295 29572 29572 W GodotPluginRegistry: 	at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:71)
02-11 15:31:08.295 29572 29572 W GodotPluginRegistry: 	at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:103)
02-11 15:31:08.295 29572 29572 W GodotPluginRegistry: 	at org.godotengine.godot.Godot.onCreate(Godot.java:575)
02-11 15:31:08.295 29572 29572 W GodotPluginRegistry: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.remoteconfig.FirebaseRemoteConfig" on path: DexPathList[[zip file "/data/app/np.com.teslatech.callbreakgodot-S1L6V2A7nfOSXYjQkX0pbA==/base.apk"],nativeLibraryDirectories=[/data/app/np.com.teslatech.callbreakgodot-S1L6V2A7nfOSXYjQkX0pbA==/lib/arm, /data/app/np.com.teslatech.callbreakgodot-S1L6V2A7nfOSXYjQkX0pbA==/base.apk!/lib/armeabi-v7a, /system/lib]]`

**Comment by DrMoriarty** [comment]
https://gist.github.com is perfect for logs

**Comment by DrMoriarty** [comment]
I updated plugin to v0.1.1
check it please

**Comment by maihomahesh** [comment]
Thank you very very much. It now works.
